ADA-1359 - Make scrollbar visible on keyboard navigation
kaltura/playkit-js-playlist pull request #63
Opened 2024-07-04 07:42 UTC by valentinStoicaK

Changes to make the scrollbar visible on keyboard navigation:
- Setting elements tabindex=0;
- Handle focus and blur events;
- Handle keyboard navigation events;

2024-07-04 08:45 UTC, semarche-kaltura requested changes

2024-07-04 08:45 UTC, semarche-kaltura commented on src/components/playlist-wrapper/index.tsx
> +      if (event.key === 'ArrowUp' || event.key === 'ArrowDown' || event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
use `KalturaPlayer.ui.utils.KeyMap` enums, like https://github.com/kaltura/playkit-js-playlist/pull/63/files#diff-83152c0966679b20b135275da0db959c7fc3ce3770372985f412ab15cdb73b25R9

Add more key-codes if needed

2024-07-04 09:22 UTC, valentinStoicaK commented on src/components/playlist-wrapper/index.tsx
> +const SCROLL_BAR_TIMEOUT = 500;
You are right! I've seen that the scrollbar disappears very fast, even for me. I'm thinking that it is not very accessible. But it's just my opinion. Should i remove the change?

2024-07-17 11:33 UTC, SivanA-Kaltura requested changes

2024-07-17 11:33 UTC, SivanA-Kaltura commented on src/components/playlist-wrapper/index.tsx
> +const SCROLL_BAR_TIMEOUT = 500;
If you want to make a visual change please confirm it with product first. If they approve you can add it.

2024-07-17 11:39 UTC, valentinStoicaK commented on src/components/playlist-wrapper/index.tsx
> +const SCROLL_BAR_TIMEOUT = 500;
I think I'll just remove the change, because it would make the app inconsistent as you said

2024-07-22 14:28 UTC, valentinStoicaK commented on src/components/playlist-wrapper/index.tsx
> +      if (event.key === 'ArrowUp' || event.key === 'ArrowDown' || event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
done

2024-07-24 07:30 UTC, semarche-kaltura approved these changes

2024-08-06 13:51 UTC, valentinStoicaK commented
@SivanA-Kaltura I am done with your changes. Can you approve?

2024-08-07 07:56 UTC, SivanA-Kaltura approved these changes

2024-08-07 14:50 UTC, merged